services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: travel_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - '3000:3000'
    command: npm run start:prod

volumes:
  pgdata:
